---
- hosts: puppetmaster
  gather_facts: true
  become_method: su
  become_user: root
  vars_files: .vault_files/my_vars.secret
  tasks:

    - name: root test
      ansible.builtin.command: 
          cmd: id
      become: true
      become_password: "{{ vault_ansible_become_pass }}"
      register: root
      ignore_errors: true
...