---
all:
children:
ios:
  vars:
    ansible_network_os: ios
    ansible_connection: ansible.netcommon.network_cli
  hosts:
    dns:
      ansible_port: 22
      ansible_host: 192.168.20.4
kvm_vlan30:
  hosts:
    win10-vm:
      ansible_host: 192.168.30.30
      ansible_port: 5985
      ansible_user: ansible_user
      ansible_password: ansible_pwd
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_message_encryption: auto
